server:
  port: 8088
---
spring:
  profiles: default
#  config:
#    activate:
#      on-profile: default
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://8080-acmexii-keycloak-e4sx0hq4jow.ws-us63.gitpod.io/realms/my_realm
        registration:
          keycloak:
            provider: keycloak
            client-id: spring-gateway-client
            client-secret: ssdlClaSA8rCqkbAy0TW5YEpjyZ3yWGl
            authorization-grant-type: authorization_code
            #redirect-uri: https://8080-acmexii-keycloak-e4sx0hq4jow.ws-us63.gitpod.io/login/oauth2/code/keycloak
            #redirect-uri: https://8080-acmexii-keycloak-e4sx0hq4jow.ws-us63.gitpod.io/login/oauth2/code/spring-gateway-client
            redirect-uri: https://8088-acmexii-keycloak-e4sx0hq4jow.ws-us63.gitpod.io/login/oauth2/code/spring-gateway-client
            scope: openid
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /order/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
---
spring:
  profiles: docker
#  config:
#    activate:
#      on-profile: docker
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://keycloak:8080/realms/my_realm
        registration:
          keycloak-spring-gateway-client:
            provider: my-keycloak-provider
            client-id: spring-gateway-client
            client-secret: HKFKYP7kb8OMldAgfvnk27FhRPOv8Y7H
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: order
          uri: http://order:8081
          predicates:
            - Path=/orders/**, /order/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
server:
  port: 8080